Algoritmo "soma"
Var
// Seção de Declarações das variáveis 
num1,num2,soma: inteiro
Inicio
// Solicitar 2 números e pedir a soma desses dois
escreva("Digite o primeiro número: ")
leia(num1)

escreval(" ")

escreva("Digite o segundo número: ")
leia(num2)

escreval(" ")
soma <- num1+num2

escreval("O resultado de",num1," +",num2," é:",soma)
//ou pode também fazer da seguinte forma
escreval("O resultado de",num1," +",num2," é:",num1+num2)

Fimalgoritmo