Algoritmo "CASO"

Var
num:inteiro

Inicio
escreval("----------------------")
escreval("   SISTEMA DE HOTEL")
escreval("----------------------")


escreval("[1] <- DOAR 10 REAIS")
escreval("[2] <- DOAR 20 REAIS")
escreval("[3] <- DOAR 30 REAIS")
escreval("[0] <- SAIR")
leia(num)


escolha num
 caso 1
  escreval("obrigado pae")
 caso 2
  escreval("obrigado pae")
 caso 3
  escreval("obrigado pae")
 caso 0

 fimescolha

Fimalgoritmo