Algoritmo "ENQUANTO2"

Var
// Seção de Declarações das variáveis
i,val,val2,salto:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Qual número vai começar? ")
leia(val)
escreva("Até onde vai? ")
leia(val2)
escreva("Qual o intervalo de salto? ")
leia(salto)


i <- val
escreval("")
  enquanto i <= val2 faca
    escreva(i," ")
      i <- i + salto
fimenquanto

Fimalgoritmo