Algoritmo "LENDOSOMA"

Var
reai,dolar:real
i,conv:inteiro
Inicio
i <- 1

escreva("Quantas vezes vai querer fazer a conversão: ")
leia(conv)
escreval("----------------------------------------------")

enquanto i <= conv faca

escreva("Qual o valor em reais: ")
leia(reai)

dolar <- reai/5.70

escreval("O valor convertido para dolar é: ",dolar:5:2)

i <- i + 1
escreval("---------------------------------------------")
fimenquanto
Fimalgoritmo